.TH MSG 3
.SH NAME
sstart, cstart, stoc, ctos, sfromc, cfroms, sstop, cstop \- simple message communication abstraction over UNIX domain sockets.
.SH SYNOPSIS
.B #include <msg.h>
.br
.B void sstart(int, char*);
.br
.B void cstart(char*);
.br
.B ssize_t stoc(int, void*, size_t);
.br
.B ssize_t ctos(void*, size_t);
.br
.B ssize_t sfromc(int, void*, size_t);
.br
.B ssize_t cfroms(void*, size_t);
.br
.B void sstop(void);
.br
.B void cstop(void);
.br

.SH DESCRIPTION
To do!
.SH NOTES
To do!
